### ISSUE TITLE
Excel单元格为空, 采用Map导入报错

### ISSUE THREAD

**Issue by arccode** [SargerasWang/ExcelUtil#10]
错误: Cannot get a STRING value from a NUMERIC cell. 

修改如下,希望作者加入master

ExcelUtil.java(448行)

for (String k : titleMap.keySet()) {
    Integer index = titleMap.get(k);
    Cell cell = row.getCell(index);
    // 判空
    if (cell == null) {
        map.put(k, null);
    } else {
        cell.setCellType(CellType.STRING);
        String value = cell.getStringCellValue();
        map.put(k, value);
    }
}

**Comment by SargerasWang** [comment]
已修改
