### ISSUE TITLE
列宽自适应 升级jar包

### ISSUE THREAD

**Issue by chengwengao** [SargerasWang/ExcelUtil#9]
感谢楼主的分享，不过在使用过程中设置的列宽自适应仍然不会生效，部分方法已过时，作者如果有时间要是能升级这2块就完美了！

**Comment by SargerasWang** [comment]
![image](https://user-images.githubusercontent.com/4179595/31772880-917628c2-b4a6-11e7-848f-ce897db11c62.png)
如图,自动列宽看起来是可以的,另,根据你的建议,已更新poi版本并修改废弃的调用方式
